name: linting, testing, building

on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs: 
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

      - name: Unit testing
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        run: docker run -d -p 6006:6006 --name my-app-container my-app

      - name: Wait for Storybook to load
        run: sleep 10

      - name: Screenshot testing
        run: docker exec my-app-container npm run test:ui:ci

      - name: Stop and remove container
        run: docker stop my-app-container && docker rm my-app-container
