name: linting, testing, building

on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs: 
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
 
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -fv

          # Manually install Archivo font using the correct URL
          mkdir -p ~/.fonts
          curl -L -o ~/.fonts/Archivo.zip https://github.com/google/fonts/archive/main.zip
          unzip ~/.fonts/Archivo.zip -d ~/.fonts/ && fc-cache -fv

      - name: Build production project
        run: npm run build:prod

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

      - name: Unit testing
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Start Storybook server
        run: npx http-server ./storybook-static -p 6006 & echo $! > storybook.pid

      - name: Wait for Storybook to load
        run: sleep 30

      - name: Screenshot testing
        run: npm run test:ui:ci

      - name: Stop Storybook server
        run: kill $(cat storybook.pid) || true
